api/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'ordenes', views.OrdenDeReparacionViewSet, basename='ordenes')
router.register(r'presupuestos', views.PresupuestoSerializerViewSet, basename='presupuestos')
urlpatterns = [
    path('', include(router.urls )),
    path('api-auth/', include('rest_framework.urls'), name="rest_framework") # incluye las urls de django autenthications para el framework rest
]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path, include
from web import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('web/', include('web.urls')),
    path('api/', include('api.urls')),
    
]

web/models.py
from django.db import models
from django.utils import timezone
import uuid
from django.core.exceptions import ValidationError
from django.contrib import messages


class Categoria(models.Model):
    nombre = models.CharField(max_length=60, verbose_name="Categoría")

    class Meta:
        verbose_name_plural = "Categorías"

    def __str__(self):
        return f"{self.nombre}"


class SubCategoria(models.Model):
    nombre = models.CharField(max_length=60, verbose_name="Subcategoría")
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name="categorias")

    class Meta:
        verbose_name_plural = "Subcategorías"

    def __str__(self):
        return f"{self.categoria.nombre} - {self.nombre}"


class Modelo(models.Model):
    nombre = models.CharField(max_length=100, verbose_name="Nombre del modelo")
    especificaciones = models.CharField(max_length=255, blank=True, null=True,verbose_name="Especificaciones y descripción del modelo")
    manual = models.URLField( blank=True, null=True, verbose_name="URL del manual en formato pdf")
    subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE, related_name="modelos")

    class Meta:
        verbose_name_plural = "Modelos"

    def __str__(self):
        return self.nombre


class SubCategoriaModelo(models.Model):
    subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)
    modelo = models.ForeignKey(Modelo, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['subcategoria', 'modelo'], name='unique_subcategoria_modelo')
        ]


class Accesorio(models.Model):
    nombre = models.CharField(max_length=100)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
            return  f"{self.nombre}"
    
class Proveedor(models.Model):
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=200, blank=True, default="--")
    telefono = models.CharField(max_length=20, blank=True, default="--")
    email = models.EmailField(blank=True, default="--")

    def __str__(self):
        return self.nombre

class Repuesto(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True)
    codigo = models.CharField(max_length=50)
    nombre = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)  
    costo_ultima_compra = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)  # Costo último
    costo_usd = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)  # Costo promedio USD
    stock = models.PositiveIntegerField(default=0)  
    stock_critico = models.PositiveIntegerField(default=1)
    ubicacion = models.CharField(max_length=100, blank=True, default='---')
    correo_enviado = models.BooleanField(default=False)

    def registrar_movimiento_inicial(self):
        """Registra un movimiento inicial al crear un nuevo repuesto."""
        if self.stock > 0:
            costo_inicial = self.costo_ultima_compra or self.precio
            movimiento = MovimientoStockRepuesto.objects.create(
                repuesto=self,
                tipo='entrada',
                cantidad=self.stock,
                costo_unitario=costo_inicial,
                destino='Registro inicial'
            )
            # Actualizar el costo de última compra y costo promedio
            self.costo_ultima_compra = costo_inicial
            self.actualizar_costo_promedio()
            self.save(update_fields=['costo_ultima_compra', 'costo_usd'])

    def descontar_stock(self, cantidad):
        """Descuenta una cantidad del stock actual."""
        if cantidad <= self.stock:
            self.stock -= cantidad
            self.save()
            
        else:
            raise ValidationError(f"No hay suficiente stock para el repuesto: {self.nombre}")



    def aumentar_stock(self, cantidad):
        """Aumenta el stock actual en la cantidad especificada."""
        self.stock += cantidad
        self.save()

    def calcular_costo_promedio(self):
        """Calcula el costo promedio basado en todas las compras."""
        movimientos = self.movimientostockrepuesto_set.filter(tipo='entrada')
        total_costo = sum(mov.cantidad * mov.costo_unitario for mov in movimientos if mov.costo_unitario)
        total_cantidad = sum(mov.cantidad for mov in movimientos)

        return total_costo / total_cantidad if total_cantidad > 0 else 0
    
    def actualizar_costo_promedio(self):
        """Actualiza el costo promedio en el campo costo_usd."""
        self.costo_usd = self.calcular_costo_promedio()
        self.save()

    def verificar_stock_critico(self):
        """Verifica si el stock está en o por debajo del nivel crítico."""
        return self.stock <= self.stock_critico
        # Señal para registrar automáticamente un movimiento de entrada al crear un repuesto
            
    def __str__(self):
        return f"{self.nombre} - {self.codigo}"
    



class MovimientoStockRepuesto(models.Model):
    TIPO_MOVIMIENTO = [
        ('entrada', 'Entrada'),
        ('salida', 'Salida'),
    ]
    repuesto = models.ForeignKey(Repuesto, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=10, choices=TIPO_MOVIMIENTO)
    cantidad = models.PositiveIntegerField()
    costo_unitario = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, help_text="Costo por unidad para entradas")
    costo_promedio = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, help_text="Costo promedio al momento del movimiento")  
    fecha = models.DateTimeField(auto_now_add=True)
    destino = models.CharField(max_length=100, blank=True, null=True, help_text="Número de Orden o 'Mostrador' para ventas directas")
    stock_parcial = models.PositiveIntegerField(default=0) 

    def save(self, *args, **kwargs):
        is_new = self.pk is None  # Verificar si es un movimiento nuevo

        if is_new:
            # Obtener el último movimiento para calcular el saldo parcial
            ultimo_movimiento = MovimientoStockRepuesto.objects.filter(
                repuesto=self.repuesto
            ).exclude(pk=self.pk).order_by('-fecha', '-id').first()
            
            saldo_anterior = ultimo_movimiento.stock_parcial if ultimo_movimiento else 0

            # Para el movimiento inicial, asignar directamente el stock actual
            if self.destino == 'Registro inicial':
                self.stock_parcial = self.repuesto.stock
            else:
                self.stock_parcial = saldo_anterior + (self.cantidad if self.tipo == 'entrada' else -self.cantidad)

        super().save(*args, **kwargs)  # Guardar el movimiento

        # Evitar duplicar el ajuste de stock para el movimiento inicial
        if is_new and self.destino != 'Registro inicial':
            # Actualizar el stock del repuesto
            if self.tipo == 'entrada':
                self.repuesto.aumentar_stock(self.cantidad)
                if self.costo_unitario:
                    self.repuesto.costo_ultima_compra = self.costo_unitario
                self.repuesto.actualizar_costo_promedio()
            elif self.tipo == 'salida':
                self.repuesto.descontar_stock(self.cantidad)

        # Calcular el costo promedio del movimiento
        if self.destino == 'Registro inicial':
            self.costo_promedio = self.costo_unitario or 0
        else:
            self.costo_promedio = self.repuesto.costo_usd or 0

        # Guardar nuevamente para actualizar el campo costo_promedio
        super().save(update_fields=['costo_promedio'])




class Maquina(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True)
    subcategoria = models.ForeignKey(SubCategoria, on_delete=models.SET_NULL, null=True)
    modelo = models.ForeignKey(Modelo, on_delete=models.CASCADE)
    serie = models.CharField(max_length=100)
    accesorios = models.ManyToManyField(Accesorio, related_name='maquinas', blank=True)
    garantia = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.categoria} {self.subcategoria} {self.modelo}'
    

class CondicionIVA(models.Model):
    CONSUMIDOR_FINAL = 'Consumidor Final'
    INSCRIPTO = 'inscripto'
    MONOTRIBUTISTA = 'monotributista'
    EXENTO = 'exento'

    CONDICION_IVA_CHOICES = [
        (CONSUMIDOR_FINAL, 'Consumidor Final'),
        (INSCRIPTO, 'Inscripto'),
        (MONOTRIBUTISTA, 'Monotributista'),
        (EXENTO, 'Exento'),
    ]

    nombre = models.CharField(max_length=20, choices=CONDICION_IVA_CHOICES, unique=True)

    def __str__(self):
        return self.get_nombre_display()
    
class TipoCliente(models.Model):
    DISTRIBUIDOR = 'distribuidor'
    PROVEEDOR = 'proveedor'
    PARTICULAR = 'particular'

    TIPO_CLIENTE_CHOICES = [
        (DISTRIBUIDOR, 'Distribuidor'),
        (PROVEEDOR, 'Proveedor'),
        (PARTICULAR, 'Particular'),
    ]

    nombre = models.CharField(max_length=20, choices=TIPO_CLIENTE_CHOICES, unique=True)

    def __str__(self):
        return self.get_nombre_display()                              

class Provincia(models.Model):
    nombre = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.nombre

class Cliente(models.Model):
    nombre = models.CharField(max_length=100, null=True, blank=True,verbose_name="Nombre o razon socia")
    empresa = models.BooleanField(default=False)
    razon_social = models.CharField(max_length=100, null=True, blank=True, verbose_name="Razon social")
    contacto = models.CharField(max_length=100, null=True, blank=True, verbose_name="Contacto")
    condicion_iva = models.ForeignKey(CondicionIVA, on_delete=models.CASCADE, verbose_name="Condicion IVA")

web/templates/web/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block titulo %}{% endblock %}</title>
    <script
      src="https://kit.fontawesome.com/4c9feabc71.js"
      crossorigin="anonymous"
    ></script>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <link
      rel="stylesheet"
      type="text/css"
      href = "{% static 'web/styles/base_styles.css' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static '/web/styles/fuentesycolores.css' %}"
    />
    {% block extra_css %}{% endblock %}
  </head>

  <body class="d-flex">
    {% include 'web/sidebar.html' %}
 

    <div class="wrapper d-flex flex-column min-vh-100 w-100" id="main-section-container">
      <header>
        <nav class="navbar py-0 d-flex flex-row align-items-center">
          <div class="my-3">
            <form action="{% url 'search_results' %}" method="get" class="d-flex p-3" role="search">
              <input
                class="form-control me-2"
                type="text"
                placeholder="buscar..."
                name="q"
              />
              <button class="btn btn-outline-light" type="submit">
                Buscar
              </button>
            </form>
          </div>  
          <div class="d-flex flex-row align-items-center">
            {% if messages %}
              <ul class="messages m-0 ">
                {% for message in messages %}
                <div class="alert alert-light alert-dismissible fade show" role="alert">
                {{ message|safe }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
              {% endfor %}
            </ul>
          {% endif %} 
          <div class="d-flex align-items-center p-3 my-3 text-light">
            <i class="fas fa-user me-2"></i>
            {% if user.is_authenticated %}
            <span>{{ user.username }}</span>
            {% endif %}
          </div>
          </div>
        </nav>      
    

      </header>

      {% block main %}
      {% endblock %}
    </div>
    
{% block extra_js %}

{% endblock %}
    <script src="{% static 'web/js/sidebar.js' %}"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

web/templates/web/buscar_cliente_results.html
{% extends "web/base.html" %}
{% load static %}

{% block titulo %}
Resultados de Búsqueda
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'web/styles/lista_clientes.css' %}" />
{% endblock %}

{% block main %}
<div class="container-fluid px-4 px-lg-5 mt-5">
    <h1 class="py-2">Resultados de Búsqueda</h1>
    <div class="d-flex justify-content-between">
        <div class="my-3">
            <form action="{% url 'buscar_cliente_results' %}" method="get" class="d-flex" role="search">
                <input class="form-control me-2" type="text" placeholder="Buscar cliente..." name="q"
                    value="{{ query }}" />
                <button class="btn btn-formulario" type="submit">Buscar</button>
            </form>
        </div>
        <div class="my-3">
            <a href="{% url 'crear_cliente' %}" class="btn btn-formulario mb-2">Nuevo Cliente</a>
        </div>
    </div>

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Razón Social</th>
                <th>Contacto</th>
                <th>CUIT</th>
                <th>DNI</th>
                <th>Tipo</th>
                <th>IVA</th>
                <th>Teléfono</th>
                <th>Teléfono Alt.</th>
                <th>Email</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for cliente in page_obj %}
            <tr>
                <td><a href="{% url 'detalle_cliente' cliente.id %}">{{ cliente.id }}</a></td>
                <td>{{ cliente.nombre }}</td>
                <td>{% if cliente.empresa %}{{ cliente.razon_social }}{% else %}---{% endif %}</td>
                <td>{% if cliente.contacto %}{{ cliente.contacto }}{% else %}---{% endif %}</td>
                <td>{% if cliente.cuit %}{{ cliente.cuit }}{% else %}---{% endif %}</td>
                <td>{% if cliente.dni %}{{ cliente.dni }}{% else %}---{% endif %}</td>
                <td>{{ cliente.tipo_cliente.nombre }}</td>
                <td>{{ cliente.condicion_iva.nombre }}</td>
                <td>{{ cliente.telefono }}</td>
                <td>{% if cliente.telefono_alternativo %}{{ cliente.telefono_alternativo }}{% else %}---{% endif %}</td>
                <td><a href="mailto:{{ cliente.email }}">{{ cliente.email }}</a></td>
                <td>
                    <a href="{% url 'editar_cliente' cliente.id %}">
                        <i class="fa-solid fa-pen-to-square btn-editar"></i>
                    </a>
                    <a href="{% url 'eliminar_cliente' cliente.id %}" class="btn-eliminar">
                        <i class="fa-regular fa-trash-can"></i>
                    </a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="12">No se encontraron clientes.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if is_paginated %}
    <nav aria-label="Paginación de clientes">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?q={{ query }}&page={{ page_obj.previous_page_number }}">Anterior</a>
            </li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
            <li class="page-item {% if page_obj.number == num %}active{% endif %}">
                <a class="page-link" href="?q={{ query }}&page={{ num }}">{{ num }}</a>
            </li>
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?q={{ query }}&page={{ page_obj.next_page_number }}">Siguiente</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock %}

{% block extra_js %}
{% endblock %}

web/templates/web/crear_cliente.html
{% extends "web/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block titulo %}
Crear Cliente
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'web/styles/crear_cliente.css' %}" />

{% endblock %}

{% block main %}
<div class="container w-75 mt-3">
  <h1>Crear Cliente</h1>
  <form method="post">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-6 d-flex flex-column">
        <!-- Campo Nombre -->
        <div class="form-floating mb-3">
          {{ form.nombre|add_class:"form-control" }}
          <label for="{{ form.nombre.id_for_label }}">Nombre</label>
          {{ form.nombre.errors }}
        </div>

        <!-- Campo Tipo Cliente y Condición IVA -->
        <div class="row">
          <div class="col-md-6">
            <div class="form-floating mb-3">
              {{ form.tipo_cliente|add_class:"form-select" }}
              <label for="{{ form.tipo_cliente.id_for_label }}">Tipo Cliente</label>
              {{ form.tipo_cliente.errors }}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-floating mb-3">
              {{ form.condicion_iva|add_class:"form-select" }}
              <label for="{{ form.condicion_iva.id_for_label }}">Condición IVA</label>
              {{ form.condicion_iva.errors }}
            </div>
          </div>
        </div>

        <!-- Recuadro Empresa -->
        <div class="p-3 mb-3" style="background-color: #f5f5f5; border-radius: 5px;">
          <h5>Empresa</h5>
          <div class="input-group mb-3">
            <div class="input-group-text">
              {{ form.empresa|add_class:"form-check-input mt-0" }}
            </div>
            <div class="form-floating flex-grow-1">
              {{ form.razon_social|add_class:"form-control" }}
              <label for="{{ form.razon_social.id_for_label }}">Razón Social</label>
            </div>
          </div>

          <div class="form-floating mb-3">
            {{ form.cuit|add_class:"form-control" }}
            <label for="{{ form.cuit.id_for_label }}">CUIT</label>
            {{ form.cuit.errors }}
          </div>

          <div class="form-floating mb-3">
            {{ form.contacto|add_class:"form-control" }}
            <label for="{{ form.contacto.id_for_label }}">Contacto</label>
            {{ form.contacto.errors }}
          </div>
        </div>

        <!-- Recuadro Particular -->
        <div class="p-3 mb-3" style="background-color: #f5f5f5; border-radius: 5px;">
          <h5>Particular</h5>
          <div class="form-floating mb-3">
            {{ form.dni|add_class:"form-control" }}
            <label for="{{ form.dni.id_for_label }}">DNI</label>
            {{ form.dni.errors }}
          </div>
        </div>
      </div>
      <!-- Resto de los campos -->

      <div class="col-md-6 d-flex flex-column">
        {% for field in form %}
        {% if field.name not in "nombre tipo_cliente condicion_iva empresa razon_social cuit contacto dni" %}
        <div class="form-floating mb-3">
          {{ field|add_class:"form-control" }}
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field.errors }}
        </div>
        {% endif %}
        {% endfor %}
        <div class="d-grid d-md-block mt-1">
          <button type="submit" class="btn btn-lg btn-formulario">Guardar</button>
        </div>

      </div>

    </div>

  </form>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script>
  document.getElementById('id_cuit').addEventListener('input', function (e) {
    let cuit = e.target.value.replace(/\D/g, '');
    if (cuit.length > 2) cuit = cuit.slice(0, 2) + '-' + cuit.slice(2);
    if (cuit.length > 10) cuit = cuit.slice(0, 11) + '-' + cuit.slice(11);
    e.target.value = cuit;
  });
</script>

{% endblock %}

web/templates/web/crear_orden.html
{% extends "web/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block titulo %}
Crear Orden
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'web/styles/crear_orden.css' %}" />
{% endblock %}

{% block main %}
<div class="container w-75 mt-3">
    <h1 class="text-center py-3">Crear Orden de Reparación</h1>
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                {% for field in orden_form %}
                {% if field.name == "cliente" %}
                <div class="form-floating mb-3">
                    {{ field|add_class:"form-control cliente-select" }}
                    <label for="{{ field.id_for_label }}">Cliente</label>
                </div>
                {% else %}
                <div class="form-floating mb-3">
                    {{ field|add_class:"form-control" }}
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                </div>
                {% endif %}
                {{ field.errors }}
                {% endfor %}
            </div>

            <div class="col-md-6">
                {% for field in maquina_form %}
                {% if field.name == "garantia" %}
                <div class="form-check mb-3">
                    {{ field|add_class:"form-check-input" }}
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                </div>
                {% else %}
                {% if field.name == "accesorios" %}
                <div class="form-floating mb-3">
                    {{ field|add_class:"form-control accesorios-select" }}
                    <label for="{{ field.id_for_label }}">Accesorios</label>
                </div>
                {% else %}
                <div class="form-floating mb-3">
                    {{ field|add_class:"form-control" }}
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field.errors }}
                </div>
                {% endif %}
                {% endif %}
                {% endfor %}
            </div>
        </div>

        <button type="submit" class="btn btn-formulario m-3">Crear Orden</button>
    </form>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'web/js/ajaxCrearOrden.js' %}"></script>
<script>
    $(document).ready(function () {
        $('#id_cliente').select2({
            placeholder: '------'
        }).next().addClass('cliente-select-container');

        $('#id_accesorios').select2({
            placeholder: 'Seleccione los accesorios...'
        }).next().addClass('accesorios-select-container');
    });
</script>
{% endblock %}

web/templates/web/editar_repuesto.html
{% extends "web/base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block titulo %}
Editar Repuesto
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'web/styles/crear_cliente.css' %}">
{% endblock %}

{% block main %}
<div class="container w-75 mt-3">
    <h1>Editar Repuesto</h1>
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <!-- Columna izquierda -->
            <div class="col-md-6 d-flex flex-column">
                <div class="form-floating mb-3">
                    {{ form.nombre|add_class:"form-control" }}
                    <label for="{{ form.nombre.id_for_label }}">Nombre</label>
                    {{ form.nombre.errors }}
                </div>

                <div class="form-floating mb-3">
                    {{ form.categoria|add_class:"form-select" }}
                    <label for="{{ form.categoria.id_for_label }}">Categoría</label>
                    {{ form.categoria.errors }}
                </div>

                <div class="form-floating mb-3">
                    {{ form.codigo|add_class:"form-control" }}
                    <label for="{{ form.codigo.id_for_label }}">Código</label>
                    {{ form.codigo.errors }}
                </div>

                <div class="form-floating mb-3">
                    {{ form.ubicacion|add_class:"form-control" }}
                    <label for="{{ form.ubicacion.id_for_label }}">Ubicación</label>
                    {{ form.ubicacion.errors }}
                </div>
            </div>

            <!-- Columna derecha -->
            <div class="col-md-6 d-flex flex-column">
                <div class="form-floating mb-3">
                    {{ form.precio|add_class:"form-control" }}
                    <label for="{{ form.precio.id_for_label }}">Precio (USD)</label>
                    {{ form.precio.errors }}
                </div>

                <div class="form-floating mb-3">
                    {{ form.stock_critico|add_class:"form-control" }}
                    <label for="{{ form.stock_critico.id_for_label }}">Stock Crítico</label>
                    {{ form.stock_critico.errors }}
                </div>

                <div class="d-grid d-md-block mt-1">
                    <button type="submit" class="btn btn-lg btn-formulario">Guardar</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}